title: Sharon McAllister photography
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: nature through my eyes
color:
  saturation: 0.1638298
  brandStrength: 0.5625
  lightness: 0.8125
  brandColors:
    - '#daefe8'
    - '#050505'
    - '#72979f'
    - '#3e6a99'
    - '#7b4f30'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
name: Sharon McAllister Photography
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.2893617
