name: Sharon McAllister Photography
favicon: null
layout_spectrum: 0.030738927656784654
typography_spectrum: 0.3050238990690559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5766308491583914
  lightness: 0.7163054395932704
  saturation: 0.9274620453361422
  rhythmicContrast: 0.29574635811150074
purpose: []
