name: Sharon McAllister Photography
favicon: null
layout_spectrum: 0.16068
typography_spectrum: 0.4657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#daefe8'
    - '#050505'
    - '#72979f'
    - '#3e6a99'
    - '#7b4f30'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
